### ISSUE TITLE
2.0 release (PSR-15)

### ISSUE THREAD

**Issue by mindplay-dk** [thecodingmachine/csrf-header-check-middleware#4]
It looks you implemented the migrations to `psr/http-server-middleware^1.0` back in february, but a release was never published.

What's the state of the unstable 2.x package published to Packagist?

Is there any work to be done before you can tag and release this?

I think this middleware is exactly what I've been looking for - a bare minimum of CSRF protection without developer intervention. We want our developers to use CSRF-keys on sensitive forms, of course - but this at least would provide some degree of protection against the easiest attacks.

I'm actually surprised that something like this isn't standard in every PHP stack.

Let me know if I can help :-)

**Comment by moufmouf** [comment]
Hey Rasmus!

Thanks for the compliments :)
Actually, I did not tag a release because I wanted to test it a little bit in a real project before tagging stable.
But I guess enough time has passed and to be honest, I simply forgot.

I'll tag it now.

**Comment by mindplay-dk** [comment]
For the record, just tested it in an app that uses both regular forms, file uploads, and async GET/POST requests to APIs - and it did not interfere with any of those, so 😄👍
